### ISSUE TITLE
T: Maquetación de componentes comunes y variables

### ISSUE THREAD

**Issue by elenaJO** [elenaJO/reto-tecnico#1]
**Overview**
Maquetación de componentes comunes y variables

**Issues**

- [x] Agregar variables globales #2
- [x] Agrego imágenes #3 
- [x] Maquetación de botones #4 
- [x] Maquetación de inputs y selectores #5 
- [x] Maquteación de checkbox y switch #6
